import 'dart:convert';
import 'dart:io';

void main() {
  final repoRoot = Directory.current;
  final assetsRoot = Directory(
    '${repoRoot.path}/packages/lxmusic_assets/assets',
  );
  if (!assetsRoot.existsSync()) {
    stderr.writeln(
      '[lxmusic] assets directory not found: ${assetsRoot.path}',
    );
    exitCode = 1;
    return;
  }

  final files = assetsRoot
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('.yaml'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final output = StringBuffer()
    ..writeln('// Generated by tools/generate_yaml_assets.dart. Do not edit.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('final Map<String, String> bundledYamlAssetTexts = <String, String>{');

  for (final file in files) {
    final relativePath = _normalizePath(
      file.path.substring(assetsRoot.path.length + 1),
    );
    output.writeln(
      '  ${jsonEncode(relativePath)}: ${jsonEncode(file.readAsStringSync())},',
    );
  }

  output
    ..writeln('};')
    ..writeln();

  final target = File(
    '${repoRoot.path}/packages/lxmusic_assets/lib/src/generated/yaml_assets.g.dart',
  );
  target.parent.createSync(recursive: true);
  target.writeAsStringSync(output.toString());
  stdout.writeln('[lxmusic] wrote ${target.path}');
}

String _normalizePath(String path) => path.replaceAll('\\', '/');
